### ISSUE TITLE
Update to 1.18.2

### ISSUE THREAD

**Issue by OutCraft-Mods** [StopModReposts/Splash-Screen-Mod#17]
This is not really an Issue, but I don't know where to put this else.
I recently found this project and liked the Idea behind it very much. So I wanted to help and because I'm a forge modder I updated the mod to 1.18.2. I hope this helps 😄

**Comment by d-513** [comment]
Please make a Pull Request with the changes

**Comment by OutCraft-Mods** [comment]
Sadly doesn't work:
"There isn’t anything to compare.
StopModReposts:master and OutCraft-Mods:1.18.2 are entirely different commit histories."

**Comment by OutCraft-Mods** [comment]
Ok I just uploaded it to a fork: https://github.com/OutCraft-Mods/Splash-Screen-Mod/tree/1.18.2
Pull request still isn't working

**Comment by d-513** [comment]
Because you forked from an old branch. Remove your repo, fork again, push to master, then PR.

**Comment by OutCraft-Mods** [comment]
Made pull request
