### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by xyroc** [StopModReposts/Splash-Screen-Mod#4]
So, ive embedded this mod into one of my mods for minecraft 1.12.2. Everything worked fine, the mod got installed correctly, but when i launch up minecraft it shows me a black screen after loading the mods. I cant seem to find any errors in the console. (And no, this is not caused by my own mod)

Am i missing something?

**Comment by xyroc** [comment]
Ive tried with this mod installed only as well. Still a black screen.

**Comment by JTK222** [comment]
I am sorry to tell you that this project is kinda dead.
It didn't receive a lot of support from modders, and I had to much stuff to do in RL
I may resurrect it one day and fix all the stuff + improve it, but even if players don't mind that popup, most modders still didn't like that Idea.
